version: "3"
services:
  datascience:
    build:
      context: .
      dockerfile: ./build/Dockerfile
    image: datascience
    volumes:
      - ./data:/home/data
    ports:
      - 8888:8888
    user: root
    environment:
      - NB_USER=data
      - NB_UID=1001
      - NB_GID=1001
